
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbvixdyotrrcblwewbql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indidml4ZHlvdHJyY2Jsd2V3YnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzA4MjEsImV4cCI6MjA2MTg0NjgyMX0.q3goapHMoQUPr0in3dIIeIQgp0oy5d2UgMwgBNrbaQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: true // Added debug to see authentication issues
  }
});

// Add a listener to catch any Supabase fetch errors
if (typeof window !== 'undefined') {
  window.addEventListener('unhandledrejection', function(event) {
    if (event.reason && event.reason.toString().includes('Failed to fetch')) {
      console.error('Supabase API connection error:', event.reason);
    }
  });
}
